en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Supporting Children's Pathways. All Rights Reserved."

  title: "Supporting Children's Pathways"
  params:
    description: "Empowering children and families to thrive through quality education, mentorship, and community support."
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/accessibility/"
    ### calls to action ###
    main_cta:
      text: "Donate"
      link: "/donate/"
    footer_cta:
      text: "Donate"
      link: "/donate/"
    ### footer text ###
    theme_copyright: "[Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
    github_edit: "Edit this page on GitHub"
    privacy_policy_url: "/privacy-policy/"
    privacy_policy_text: "Privacy Policy"
    sitemap_url: "/sitemap/"
    sitemap_text: "Sitemap"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      weight: 1
    - identifier: "about-us"
      name: "About Us"
      url: "/about-us/"
      weight: 1
      post: "Learn about our background and founding"
      parent: "about"
    - identifier: "our-team"
      name: "Our Team"
      url: "/our-team/"
      weight: 2
      post: "Learn about our key team members and their roles"
      parent: "about"
    - identifier: "impact"
      name: "Impact"
      url: "/impact/"
      weight: 3
      post: "Learn about the impact of our work"
      parent: "about"
    - identifier: "initiatives"
      name: "Initiatives"
      url: "/initiatives/"
      weight: 2
    - identifier: "events"
      name: "Events"
      url: "/events/"
      weight: 3
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 4
